### ISSUE TITLE
Some valid :profile sub commands show error

### ISSUE THREAD

**Issue by errael** [lacygoill/vim9-syntax#2]
`profile stop` and `profile dump` show the sub command `stop` and `dump` as an error. I took a look at the source, but I've never worked with syntax-hl  and quickly stopped looking.

includes
```
@  changeset:   174:46ddce48cfe9
|  bookmark:    main
|  tag:         default/main
|  tag:         tip
|  user:        lagygoill <lacygoill@lacygoill.me>
|  date:        Sun May 22 21:03:29 2022 +0200
|  summary:     support bitwise shift operators
```

@lacygoill (since I don't know if you monitor these issues)

**Comment by lacygoill** [comment]
I never wrote them in a script, so I never noticed the issue.  At some point, I should probably stop hard-coding those values in the script, and instead retrieve them programmatically with `getcompletion('profile ', 'cmdline')`.

I think it should be fixed now.

**Comment by lacygoill** [comment]
> I think it should be fixed now.

[By this commit](https://github.com/lacygoill/vim9-syntax/commit/d64333b98e5fb7b63d03e1b034737989396dcb40).

**Comment by errael** [comment]
Been working, should have closed long ago
