### ISSUE TITLE
Some command-completion attributes are highlighted as `Vim9UserCmdAttrErrorValue`

### ISSUE THREAD

**Issue by bfrg** [lacygoill/vim9-syntax#4]
Some of the `command-completion` attributes are highlighted as a syntax error. Example:
```vim
vim9script

command -nargs=+ -complete=filetype      Test1 echo <q-args>
command -nargs=+ -complete=file          Test2 echo <q-args>
command -nargs=+ -complete=file_in_path  Test3 echo <q-args>
command -nargs=+ -complete=tag           Test4 echo <q-args>
command -nargs=+ -complete=tag_listfiles Test5 echo <q-args>
```

Screenshot:
![screenshot-2022-09-29_012157](https://user-images.githubusercontent.com/6266600/192905933-e385a3a1-11a5-4562-9b74-15fd7715a206.png)

This is because the longer attributes are short-circuited in the regex they are defined in. The order matters. Longer names should be defined first.

The following patch fixes the issue:
```diff
diff --git a/import/vim9Language.vim b/import/vim9Language.vim
index 7f5e6aa..fabd880 100644
--- a/import/vim9Language.vim
+++ b/import/vim9Language.vim
@@ -628,9 +628,9 @@ const command_complete_type_list: list<string> =<< trim END
     environment
     event
     expression
-    file
-    file_in_path
     filetype
+    file_in_path
+    file
     function
     help
     highlight
@@ -647,8 +647,8 @@ const command_complete_type_list: list<string> =<< trim END
     sign
     syntax
     syntime
-    tag
     tag_listfiles
+    tag
     user
     var
 END
```

Result:
![screenshot-2022-09-29_012202](https://user-images.githubusercontent.com/6266600/192905516-702e9838-060a-40fe-8f51-602e39113103.png)

**Comment by lacygoill** [comment]
This should have been fixed by [this commit](https://github.com/lacygoill/vim9-syntax/commit/d4c3e7c6c0792dd65ed034f7f6497255c382a0b2).
