### ISSUE TITLE
Syntax is broken when CompilerSet contains line continuations

### ISSUE THREAD

**Issue by bfrg** [lacygoill/vim9-syntax#5]
`errorformat` can be quite long. So I often split it across multiple lines. I've noticed that this isn't supported yet.

Example:
```vim
vim9script

CompilerSet errorformat=
        \%D%*\\a[%*\\d]:\ Entering\ directory\ %*[`']%f',
        \%X%*\\a[%*\\d]:\ Leaving\ directory\ %*[`']%f',
        \%D%*\\a:\ Entering\ directory\ %*[`']%f',
        \%X%*\\a:\ Leaving\ directory\ %*[`']%f'
```

![screenshot-2022-10-03_002039](https://user-images.githubusercontent.com/6266600/193478887-9817eb54-7d27-4904-8762-68198d7162af.png)

**Comment by lacygoill** [comment]
I tried to fix the issue in these commits:

- cb469b875aa9d0bc21b70c963da305c10f95f87f
- b38e9418a46c93314a81d04728ce4e705ad815e0
- 07f34be432320b8f5c376ea342ffcca9c1726fec

But it breaks this snippet:
```vim
vim9script
setlocal foldexpr=getline(v:lnum)=~'^#'?'>1':'='
ls
```
`ls` should be highlighted as a command; instead it's highlighted as an option.

Not sure how to fix this at the moment.  If you have an idea, let me know.  Although, the code is already quite complex.  Not sure I want to add more complexity.  FWIW, I try to avoid explicit line continuations as much as possible.  For example, here, I would re-write the code like this:
```vim
vim9script
var value: list<string> =<< trim END
    %D%*\a[%*\d]: Entering directory %*[`']%f'
    %X%*\a[%*\d]: Leaving directory %*[`']%f'
    %D%*\a: Entering directory %*[`']%f'
    %X%*\a: Leaving directory %*[`']%f'
END
$'CompilerSet errorformat={value->join(',')}'->execute()
```
As a benefit, there is no need to double the backslashes, nor to escape the spaces, which makes the value easier to read and maintain.  Here, I doubt the `execute()` makes a significant difference performance-wise.

What could also help is a `compilerset()` function which would work as a replacement for `:CompilerSet`.  In a function call, it's easier to split and format a long string expression.  Or maybe a more general `setoption()` function, which would accept some argument to let it work as a replacement for `:CompilerSet`, in addition to `:set`, `:setlocal`, `:setglobal`.

**Comment by lacygoill** [comment]
> But it breaks this snippet:

Which is why I had to revert the commits.

**Comment by bfrg** [comment]
Thank you for doing this. I tried something similar before opening this issue and encountered the exact same problem. I didn't have time to go through the entire syntax file. I'll take a look at it again when I have more time.

The `heredoc` is a good alternative.
